import type { CombatModifier } from "../types/combat.ts";
import type { ActionType, CoreStatId, PowerId } from "../types/game.ts";
import type { PowerActionType } from "../types/powers.ts";

export interface RuntimePowerLevelMechanics {
  level: number;
  actionType: PowerActionType | null;
  manaCost: number;
  durationRounds: number | null;
  maintenanceManaCost: number | null;
  castMode: "none" | "buff" | "damage" | "healing" | "control" | "summon";
  passiveModifiers: CombatModifier[];
  activeModifiers: CombatModifier[];
  selectedPhysicalStatBonus: number | null;
  directDamageBonus: number | null;
  directHealingBonus: number | null;
  statusId: string | null;
  summonCount: number | null;
  summonTemplateLabel: string | null;
}

export interface RuntimePowerDefinition {
  id: PowerId;
  name: string;
  governingStat: CoreStatId;
  levels: RuntimePowerLevelMechanics[];
}

const BR_LEVELS: RuntimePowerLevelMechanics[] = [
  {
    level: 1,
    actionType: "standard",
    manaCost: 2,
    durationRounds: 3,
    maintenanceManaCost: null,
    castMode: "buff",
    passiveModifiers: [],
    activeModifiers: [],
    selectedPhysicalStatBonus: 1,
    directDamageBonus: null,
    directHealingBonus: null,
    statusId: null,
    summonCount: null,
    summonTemplateLabel: null,
  },
  {
    level: 2,
    actionType: "standard",
    manaCost: 2,
    durationRounds: 3,
    maintenanceManaCost: null,
    castMode: "buff",
    passiveModifiers: [],
    activeModifiers: [],
    selectedPhysicalStatBonus: 1,
    directDamageBonus: null,
    directHealingBonus: null,
    statusId: null,
    summonCount: null,
    summonTemplateLabel: null,
  },
  {
    level: 3,
    actionType: "standard",
    manaCost: 3,
    durationRounds: 3,
    maintenanceManaCost: null,
    castMode: "buff",
    passiveModifiers: [],
    activeModifiers: [],
    selectedPhysicalStatBonus: 2,
    directDamageBonus: null,
    directHealingBonus: null,
    statusId: null,
    summonCount: null,
    summonTemplateLabel: null,
  },
  {
    level: 4,
    actionType: "standard",
    manaCost: 3,
    durationRounds: 3,
    maintenanceManaCost: null,
    castMode: "buff",
    passiveModifiers: [],
    activeModifiers: [{ target: "damage_reduction", value: 1 }],
    selectedPhysicalStatBonus: 2,
    directDamageBonus: null,
    directHealingBonus: null,
    statusId: null,
    summonCount: null,
    summonTemplateLabel: null,
  },
  {
    level: 5,
    actionType: "standard",
    manaCost: 4,
    durationRounds: 3,
    maintenanceManaCost: null,
    castMode: "buff",
    passiveModifiers: [],
    activeModifiers: [{ target: "damage_reduction", value: 2 }],
    selectedPhysicalStatBonus: 3,
    directDamageBonus: null,
    directHealingBonus: null,
    statusId: null,
    summonCount: null,
    summonTemplateLabel: null,
  },
];

export const powerRuntimeLibrary: Record<PowerId, RuntimePowerDefinition> = {
  awareness: {
    id: "awareness",
    name: "Awareness",
    governingStat: "PER",
    levels: [
      {
        level: 1,
        actionType: null,
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: null,
        castMode: "none",
        passiveModifiers: [],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 2,
        actionType: null,
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: null,
        castMode: "none",
        passiveModifiers: [],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 3,
        actionType: null,
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: null,
        castMode: "none",
        passiveModifiers: [{ target: "initiative", value: 1 }],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 4,
        actionType: null,
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: null,
        castMode: "none",
        passiveModifiers: [{ target: "initiative", value: 1 }],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 5,
        actionType: null,
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: null,
        castMode: "none",
        passiveModifiers: [{ target: "initiative", value: 2 }],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
    ],
  },
  body_reinforcement: {
    id: "body_reinforcement",
    name: "Body Reinforcement",
    governingStat: "STAM",
    levels: BR_LEVELS,
  },
  crowd_control: {
    id: "crowd_control",
    name: "Crowd Control",
    governingStat: "CHA",
    levels: [
      {
        level: 1,
        actionType: "standard",
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: 1,
        castMode: "control",
        passiveModifiers: [],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: "crowd_controlled",
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 2,
        actionType: "standard",
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: 1,
        castMode: "control",
        passiveModifiers: [],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: "crowd_controlled",
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 3,
        actionType: "standard",
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: 1,
        castMode: "control",
        passiveModifiers: [],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: "crowd_controlled",
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 4,
        actionType: "bonus",
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: 1,
        castMode: "control",
        passiveModifiers: [],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: "crowd_controlled",
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 5,
        actionType: "bonus",
        manaCost: 0,
        durationRounds: null,
        maintenanceManaCost: 1,
        castMode: "control",
        passiveModifiers: [],
        activeModifiers: [],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: "crowd_controlled",
        summonCount: null,
        summonTemplateLabel: null,
      },
    ],
  },
  elementalist: {
    id: "elementalist",
    name: "Elementalist",
    governingStat: "INT",
    levels: [1, 2, 3, 4, 5].map((level) => ({
      level,
      actionType: "standard",
      manaCost: level,
      durationRounds: null,
      maintenanceManaCost: null,
      castMode: "damage",
      passiveModifiers: [],
      activeModifiers: [],
      selectedPhysicalStatBonus: null,
      directDamageBonus: level,
      directHealingBonus: null,
      statusId: null,
      summonCount: null,
      summonTemplateLabel: null,
    })),
  },
  healing: {
    id: "healing",
    name: "Healing",
    governingStat: "INT",
    levels: [1, 2, 3, 4, 5].map((level) => ({
      level,
      actionType: "standard",
      manaCost: level,
      durationRounds: null,
      maintenanceManaCost: null,
      castMode: "healing",
      passiveModifiers: [],
      activeModifiers: [],
      selectedPhysicalStatBonus: null,
      directDamageBonus: null,
      directHealingBonus: level,
      statusId: null,
      summonCount: null,
      summonTemplateLabel: null,
    })),
  },
  light_support: {
    id: "light_support",
    name: "Light Support",
    governingStat: "APP",
    levels: [
      {
        level: 1,
        actionType: "bonus_or_standard",
        manaCost: 2,
        durationRounds: 3,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [{ target: "successes_to_any_roll", value: 1 }],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 2,
        actionType: "bonus_or_standard",
        manaCost: 3,
        durationRounds: 3,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [
          { target: "successes_to_any_roll", value: 2 },
          { target: "damage_reduction", value: 1 },
        ],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 3,
        actionType: "bonus_or_standard",
        manaCost: 4,
        durationRounds: 3,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [
          { target: "successes_to_any_roll", value: 3 },
          { target: "damage_reduction", value: 1 },
          { target: "soak", value: 1 },
        ],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 4,
        actionType: "bonus_or_standard",
        manaCost: 5,
        durationRounds: 4,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [
          { target: "successes_to_any_roll", value: 3 },
          { target: "damage_reduction", value: 2 },
          { target: "soak", value: 1 },
        ],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 5,
        actionType: "bonus_or_standard",
        manaCost: 6,
        durationRounds: 5,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [
          { target: "successes_to_any_roll", value: 4 },
          { target: "damage_reduction", value: 2 },
          { target: "soak", value: 2 },
        ],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
    ],
  },
  necromancy: {
    id: "necromancy",
    name: "Necromancy",
    governingStat: "APP",
    levels: [1, 2, 3, 4, 5].map((level) => ({
      level,
      actionType: "standard",
      manaCost: Math.max(1, level - 1),
      durationRounds: null,
      maintenanceManaCost: null,
      castMode: "summon",
      passiveModifiers: [],
      activeModifiers: [],
      selectedPhysicalStatBonus: null,
      directDamageBonus: null,
      directHealingBonus: null,
      statusId: null,
      summonCount: level >= 2 ? 2 : 1,
      summonTemplateLabel: level >= 2 ? "skeleton_pack" : "simple_skeleton",
    })),
  },
  shadow_control: {
    id: "shadow_control",
    name: "Shadow Control",
    governingStat: "MAN",
    levels: [
      {
        level: 1,
        actionType: "bonus_or_standard",
        manaCost: 2,
        durationRounds: 3,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [{ target: "armor_class", value: 1 }],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 2,
        actionType: "bonus_or_standard",
        manaCost: 3,
        durationRounds: 3,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [{ target: "armor_class", value: 2 }],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 3,
        actionType: "bonus_or_standard",
        manaCost: 4,
        durationRounds: 4,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [
          { target: "armor_class", value: 2 },
          { target: "successes_to_any_roll", value: 1 },
        ],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 4,
        actionType: "bonus_or_standard",
        manaCost: 5,
        durationRounds: 4,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [
          { target: "armor_class", value: 3 },
          { target: "successes_to_any_roll", value: 1 },
        ],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: null,
        summonTemplateLabel: null,
      },
      {
        level: 5,
        actionType: "bonus_or_standard",
        manaCost: 6,
        durationRounds: 5,
        maintenanceManaCost: null,
        castMode: "buff",
        passiveModifiers: [],
        activeModifiers: [
          { target: "armor_class", value: 3 },
          { target: "successes_to_any_roll", value: 2 },
        ],
        selectedPhysicalStatBonus: null,
        directDamageBonus: null,
        directHealingBonus: null,
        statusId: null,
        summonCount: 1,
        summonTemplateLabel: "shadow_soldier",
      },
    ],
  },
};

export function getRuntimePowerLevel(
  powerId: PowerId,
  level: number
): RuntimePowerLevelMechanics | null {
  const definition = powerRuntimeLibrary[powerId];
  return definition.levels.find((entry) => entry.level === level) ?? null;
}

export function getKnownPowerLevel(
  knownPowers: Partial<Record<PowerId, number>>,
  powerId: PowerId
): number {
  return Math.max(0, Math.floor(knownPowers[powerId] ?? 0));
}

export function isActionCompatibleWithPower(
  requestedAction: ActionType,
  actionType: PowerActionType | null
): boolean {
  if (actionType === null) {
    return false;
  }

  if (actionType === "bonus_or_standard") {
    return requestedAction === "bonus" || requestedAction === "standard";
  }

  if (actionType === "bonus_plus_standard") {
    return requestedAction === "standard";
  }

  return requestedAction === actionType;
}
